version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
words: []
ignoreWords:
  - Animall
  - Animes
  - Mangas
  - moti
  - nent
  - tamagui
  - typecheck
  - unimodules
import: []
